Make it possible to delete and recreate the Pod, on the existing Volume.
Addressing
$ kubectl delete pod/kind-cluster
pod "kind-cluster" deleted
$ kubectl apply -f - < kind-cluster-pod-k3s.yaml
persistentvolumeclaim/kind-pvc unchanged
pod/kind-cluster created
configmap/podman-config unchanged
$ kubectl logs -f pod/kind-cluster -c create-cluster
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
ERROR: failed to create cluster: node(s) already exist for a cluster with the name "kind"

The create-or-ignore logic in the create-cluster init container will be easier in separate script.