On rootful podman, the kind network seems to get created in /etc and thus not preserved in the volume.
Addressing
$ sudo podman exec -ti kind podman start --all
Error: unable to start container "06406ab7c8eb1669e6e0202e6b6ecf81f19fa05b992f7aa8345e249668b74483": unable to find network with name or ID kind: network not found